# Generated by Django 2.2.2 on 2019-06-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('email', models.EmailField(max_length=30, primary_key=True, serialize=False)),
                ('c_date', models.DateField(auto_now_add=True)),
                ('comment', models.TextField()),
            ],
        ),
    ]
